main: nl.skelic.as.Core
name: AttractionStatus
version: 1.4
author: SkelicStylz
description: AttractionStatus Plugin is made for Amusement park servers.
commands:
  attractiestatus:
    description: This command is used for every AttractionStatus commands!
    aliases: [as, astatus]
    permission: attractionstatus.*
    permission-message: Sorry, you don't have permission to use this command!
  attracties:
    description: This opens the Attractions menu.
    permission: attractionstatus.attractions
    aliases: [att]
    permission-message: Sorry, you don't have permission to use this command!
  zones:
    description: This opens the Zone menu.
    permission: attractionstatus.zones
    permission-message: Sorry, you don't have permission to use this command!