main: nl.skelic.as.Core
name: AttractieStatus
version: 1.2
author: SkelicStylz
description: AttractieStatus Plugin is gemaakt voor PretPark servers.
commands:
  attractiestatus:
    description: Dit commando word gebruikt voor alle AttractieStatus Functiens,
    aliases: [as, astatus]
    permission: attractiestatus.*
    permission-message: Sorry je hebt geen permissie om dit comand uit te voeren!
  attracties:
    description: Dit opent het Attracties Menu.
    permission: attractiestatus.attracties
    aliases: [att]
    permission-message: Sorry je hebt geen permissie om dit comand uit te voeren!
  zones:
    description: Dit opent het Zones Menu.
    permission: attractiestatus.zones
    permission-message: Sorry je hebt geen permissie om dit comand uit te voeren!